import { NextResponse } from 'next/server';
import pool from '@/lib/db';

const FILIERES = [
  { code: 'SLCHT1', nom: '1 ere Année : Physique', semestre: 1, short_base: 'PC1' },
  { code: 'SLIAT1', nom: '1ere année Info Appliquée', semestre: 1, short_base: 'IA1' },
  { code: 'SLPCH2', nom: '2eme anée Physique', semestre: 3, short_base: 'PH3' },
  { code: 'SLBGT1', nom: '1ere Année : Biologie', semestre: 1, short_base: 'BG1' },
  { code: 'MFBAV2', nom: 'Master BAVIA', semestre: 2, short_base: 'MB2' },
  { code: 'SLIAT2', nom: '2eme année Info Appliquee', semestre: 3, short_base: 'IA3' },
  { code: 'SLMII2', nom: '2eme annee Informatique', semestre: 3, short_base: 'IN3' },
  { code: 'SLMIT1', nom: '1ère année Informatique', semestre: 1, short_base: 'MI1' },
  { code: 'SLMIM3', nom: '3eme année Mathématiques', semestre: 5, short_base: 'MA5' },
  { code: 'SLBGB3', nom: '3eme année biologie', semestre: 5, short_base: 'BI5' },
  { code: 'SLBGB2', nom: '2eme année Biologie', semestre: 3, short_base: 'BI3' },
  { code: 'SLPCP3', nom: '3eme année Physique Moderne', semestre: 5, short_base: 'PH5' },
  { code: 'SLPCC2', nom: '2eme année Chimie', semestre: 3, short_base: 'CH3' },
  { code: 'SLGEP3', nom: '3eme année Génie Eléctrique et Energie Renouvelables', semestre: 5, short_base: 'PH5' },
  { code: 'SLMII3', nom: '3eme année Informatique', semestre: 5, short_base: 'IN5' },
  { code: 'SLCPC3', nom: '3eme année Chimie Physique', semestre: 5, short_base: 'CP5' },
  { code: 'SLMIM2', nom: '2eme année Mathématique', semestre: 3, short_base: 'MA3' },
  { code: 'SLIAI3', nom: '3 eme année Info Appliquée', semestre: 5, short_base: 'IA5' },
  { code: 'SMSGM1', nom: '1ere année Master Génie Maritime', semestre: 1, short_base: 'MGM1' },
  { code: 'SLBGG2', nom: '2eme année Géologie', semestre: 3, short_base: 'GE3' },
  { code: 'SFBVV3', nom: '3ème année BV', semestre: 3, short_base: 'SFV3' },
  { code: 'SBENV2', nom: '2eme année Master SBENV', semestre: 2, short_base: 'SBE2' },
  { code: 'SFPCC3', nom: '3ème année chimie', semestre: 3, short_base: 'SFC3' },
  { code: 'SFPCP3', nom: '3ème année SMP', semestre: 3, short_base: 'SFP3' },
  { code: 'SLBGG3', nom: '3eme année géologie', semestre: 5, short_base: 'GE5' },
  { code: 'SFAII3', nom: '3eme année maths appliquées', semestre: 3, short_base: 'SFA3' },
];

const MODULES = [
  { filiere_code: 'SLCHT1', code: 'SLPC1105', nom: 'algebre1', semestre: 1, short: 'PC1' },
  { filiere_code: 'SLCHT1', code: 'SLPC1205', nom: 'analyse 1', semestre: 1, short: 'PC1' },
  { filiere_code: 'SLCHT1', code: 'SLPC1305', nom: 'atomistique', semestre: 1, short: 'PC1' },
  { filiere_code: 'SLCHT1', code: 'SLPC1405', nom: 'thermochimie', semestre: 1, short: 'PC1' },
  { filiere_code: 'SLCHT1', code: 'SLPC1505', nom: 'thermodynamique', semestre: 1, short: 'PC1' },
  { filiere_code: 'SLCHT1', code: 'SLPC1605', nom: 'mécanique du point', semestre: 1, short: 'PC1' },
  { filiere_code: 'SLCHT1', code: 'SLPC1705', nom: 'MTU', semestre: 1, short: 'PC1' },
  { filiere_code: 'SLCHT1', code: 'SLPC2105', nom: 'algebre1', semestre: 2, short: 'PC2' },
  { filiere_code: 'SLCHT1', code: 'SLPC2205', nom: 'analyse 1', semestre: 2, short: 'PC2' },
  { filiere_code: 'SLCHT1', code: 'SLPC2305', nom: 'atomistique', semestre: 2, short: 'PC2' },
  { filiere_code: 'SLCHT1', code: 'SLPC2405', nom: 'thermochimie', semestre: 2, short: 'PC2' },
  { filiere_code: 'SLCHT1', code: 'SLPC2505', nom: 'thermodynamique', semestre: 2, short: 'PC2' },
  { filiere_code: 'SLCHT1', code: 'SLPC2605', nom: 'mécanique du point', semestre: 2, short: 'PC2' },
  { filiere_code: 'SLCHT1', code: 'SLPC2705', nom: 'MTU', semestre: 2, short: 'PC2' },
  { filiere_code: 'SLIAT1', code: 'SLIA1105', nom: 'Analyse 1', semestre: 1, short: 'IA1' },
  { filiere_code: 'SLIAT1', code: 'SLIA1205', nom: 'Algebre 1', semestre: 1, short: 'IA1' },
  { filiere_code: 'SLIAT1', code: 'SLIA1305', nom: 'Electronique numérique', semestre: 1, short: 'IA1' },
  { filiere_code: 'SLIAT1', code: 'SLIA1405', nom: 'Algorithmique et Programa', semestre: 1, short: 'IA1' },
  { filiere_code: 'SLIAT1', code: 'SLIA1505', nom: 'Programmation Python 1', semestre: 1, short: 'IA1' },
  { filiere_code: 'SLIAT1', code: 'SLIA1605', nom: 'Architecture', semestre: 1, short: 'IA1' },
  { filiere_code: 'SLIAT1', code: 'SLIA1705', nom: 'MTU', semestre: 1, short: 'IA1' },
  { filiere_code: 'SLIAT1', code: 'SLIA2105', nom: 'Analyse 1', semestre: 2, short: 'IA2' },
  { filiere_code: 'SLIAT1', code: 'SLIA2205', nom: 'Algebre 1', semestre: 2, short: 'IA2' },
  { filiere_code: 'SLIAT1', code: 'SLIA2305', nom: 'Electronique numérique', semestre: 2, short: 'IA2' },
  { filiere_code: 'SLIAT1', code: 'SLIA2405', nom: 'Algorithmique et Programa', semestre: 2, short: 'IA2' },
  { filiere_code: 'SLIAT1', code: 'SLIA2505', nom: 'Programmation Python 1', semestre: 2, short: 'IA2' },
  { filiere_code: 'SLIAT1', code: 'SLIA2605', nom: 'Architecture', semestre: 2, short: 'IA2' },
  { filiere_code: 'SLIAT1', code: 'SLIA2705', nom: 'MTU', semestre: 2, short: 'IA2' },
  { filiere_code: 'SLPCH2', code: 'SLPH3105', nom: 'Mecanique du solide', semestre: 3, short: 'PH3' },
  { filiere_code: 'SLPCH2', code: 'SLPH3205', nom: 'Circuit électriques', semestre: 3, short: 'PH3' },
  { filiere_code: 'SLPCH2', code: 'SLPH3305', nom: 'Electromagnétisme', semestre: 3, short: 'PH3' },
  { filiere_code: 'SLPCH2', code: 'SLPH3405', nom: 'Chimie organique générale', semestre: 3, short: 'PH3' },
  { filiere_code: 'SLPCH2', code: 'SLPH3605', nom: 'Mathematique physique', semestre: 3, short: 'PH3' },
  { filiere_code: 'SLPCH2', code: 'SLPH3505', nom: 'Thermodynamique 2', semestre: 3, short: 'PH3' },
  { filiere_code: 'SLPCH2', code: 'SLPH3705', nom: 'Langues', semestre: 3, short: 'PH3' },
  { filiere_code: 'SLPCH2', code: 'SLPH4105', nom: 'Mecanique du solide', semestre: 4, short: 'PH4' },
  { filiere_code: 'SLPCH2', code: 'SLPH4205', nom: 'Circuit électriques', semestre: 4, short: 'PH4' },
  { filiere_code: 'SLPCH2', code: 'SLPH4305', nom: 'Electromagnétisme', semestre: 4, short: 'PH4' },
  { filiere_code: 'SLPCH2', code: 'SLPH4405', nom: 'Chimie organique générale', semestre: 4, short: 'PH4' },
  { filiere_code: 'SLPCH2', code: 'SLPH4605', nom: 'Mathematique physique', semestre: 4, short: 'PH4' },
  { filiere_code: 'SLPCH2', code: 'SLPH4505', nom: 'Thermodynamique 2', semestre: 4, short: 'PH4' },
  { filiere_code: 'SLPCH2', code: 'SLPH4705', nom: 'Langues', semestre: 4, short: 'PH4' },
  { filiere_code: 'SLBGT1', code: 'SLBG1105', nom: 'Biologie cellulaire', semestre: 1, short: 'BG1' },
  { filiere_code: 'SLBGT1', code: 'SLBG1205', nom: 'Histologie et notions d\'embryologie', semestre: 1, short: 'BG1' },
  { filiere_code: 'SLBGT1', code: 'SLBG1305', nom: 'Géologie générale', semestre: 1, short: 'BG1' },
  { filiere_code: 'SLBGT1', code: 'SLBG1405', nom: 'Atomistique et laison chimique', semestre: 1, short: 'BG1' },
  { filiere_code: 'SLBGT1', code: 'SLBG1505', nom: 'Thermodynamique/mécanique', semestre: 1, short: 'BG1' },
  { filiere_code: 'SLBGT1', code: 'SLBG1605', nom: 'Mathématiques', semestre: 1, short: 'BG1' },
  { filiere_code: 'SLBGT1', code: 'SLBG1705', nom: 'MTU', semestre: 1, short: 'BG1' },
  { filiere_code: 'SLBGT1', code: 'SLBG2105', nom: 'Biologie cellulaire', semestre: 2, short: 'BG2' },
  { filiere_code: 'SLBGT1', code: 'SLBG2205', nom: 'Histologie et notions d\'embryologie', semestre: 2, short: 'BG2' },
  { filiere_code: 'SLBGT1', code: 'SLBG2305', nom: 'Géologie générale', semestre: 2, short: 'BG2' },
  { filiere_code: 'SLBGT1', code: 'SLBG2405', nom: 'Atomistique et laison chimique', semestre: 2, short: 'BG2' },
  { filiere_code: 'SLBGT1', code: 'SLBG2505', nom: 'Thermodynamique/mécanique', semestre: 2, short: 'BG2' },
  { filiere_code: 'SLBGT1', code: 'SLBG2605', nom: 'Mathématiques', semestre: 2, short: 'BG2' },
  { filiere_code: 'SLBGT1', code: 'SLBG2705', nom: 'MTU', semestre: 2, short: 'BG2' },
  { filiere_code: 'MFBAV2', code: 'MB23105', nom: 'BIOCHIMIE ALIMENTAIRE', semestre: 2, short: 'MB2' },
  { filiere_code: 'MFBAV2', code: 'MB23205', nom: 'HYGIENE ET SECURITE DES ALIMENTS', semestre: 2, short: 'MB2' },
  { filiere_code: 'MFBAV2', code: 'MB23305', nom: 'Management et Normes de la Qualité en Agroalimentaire', semestre: 2, short: 'MB2' },
  { filiere_code: 'MFBAV2', code: 'MB23405', nom: 'Stage d\'initiation', semestre: 2, short: 'MB2' },
  { filiere_code: 'MFBAV2', code: 'MB23505', nom: 'TECHNOLOGIE ALIMENTAIRE', semestre: 2, short: 'MB2' },
  { filiere_code: 'MFBAV2', code: 'MB23605', nom: 'MIROBIOLOGIE INDUSTRIELLE', semestre: 2, short: 'MB2' },
  { filiere_code: 'MFBAV2', code: 'MB23705', nom: 'NUTRITION ET ALIMENTATION', semestre: 2, short: 'MB2' },
  { filiere_code: 'SLIAT2', code: 'SLIA3105', nom: 'Programmation Web 2', semestre: 3, short: 'IA3' },
  { filiere_code: 'SLIAT2', code: 'SLIA3505', nom: 'Modélisation objet-UML', semestre: 3, short: 'IA3' },
  { filiere_code: 'SLIAT2', code: 'SLIA3705', nom: 'Langues', semestre: 3, short: 'IA3' },
  { filiere_code: 'SLIAT2', code: 'SLIA3305', nom: 'Systéme d\'exploitation1', semestre: 3, short: 'IA3' },
  { filiere_code: 'SLIAT2', code: 'SLIA3405', nom: 'Structure de données en c', semestre: 3, short: 'IA3' },
  { filiere_code: 'SLIAT2', code: 'SLIA3205', nom: 'Recherche opérationnelle', semestre: 3, short: 'IA3' },
  { filiere_code: 'SLIAT2', code: 'SLIA3605', nom: 'Probabilités et statistiques', semestre: 3, short: 'IA3' },
  { filiere_code: 'SLIAT2', code: 'SLIA4105', nom: 'Programmation Web 2', semestre: 4, short: 'IA4' },
  { filiere_code: 'SLIAT2', code: 'SLIA4505', nom: 'Modélisation objet-UML', semestre: 4, short: 'IA4' },
  { filiere_code: 'SLIAT2', code: 'SLIA4705', nom: 'Langues', semestre: 4, short: 'IA4' },
  { filiere_code: 'SLIAT2', code: 'SLIA4305', nom: 'Systéme d\'exploitation1', semestre: 4, short: 'IA4' },
  { filiere_code: 'SLIAT2', code: 'SLIA4405', nom: 'Structure de données en c', semestre: 4, short: 'IA4' },
  { filiere_code: 'SLIAT2', code: 'SLIA4205', nom: 'Recherche opérationnelle', semestre: 4, short: 'IA4' },
  { filiere_code: 'SLIAT2', code: 'SLIA4605', nom: 'Probabilités et statistiques', semestre: 4, short: 'IA4' },
  { filiere_code: 'SLMII2', code: 'SLIN3505', nom: 'architecture des ordinateurs', semestre: 3, short: 'IN3' },
  { filiere_code: 'SLMII2', code: 'SLIN3705', nom: 'Langues', semestre: 3, short: 'IN3' },
  { filiere_code: 'SLMII2', code: 'SLIN3305', nom: 'Programmation en Lang c', semestre: 3, short: 'IN3' },
  { filiere_code: 'SLMII2', code: 'SLIN3105', nom: 'Program Objet UML', semestre: 3, short: 'IN3' },
  { filiere_code: 'SLMII2', code: 'SLIN3205', nom: 'Programmation Web 1', semestre: 3, short: 'IN3' },
  { filiere_code: 'SLMII2', code: 'SLIN3405', nom: 'Systéme d\'exploitation 1', semestre: 3, short: 'IN3' },
  { filiere_code: 'SLMII2', code: 'SLIN3605', nom: 'Probabimlités et statistiques', semestre: 3, short: 'IN3' },
  { filiere_code: 'SLMII2', code: 'SLIN4505', nom: 'architecture des ordinateurs', semestre: 4, short: 'IN4' },
  { filiere_code: 'SLMII2', code: 'SLIN4705', nom: 'Langues', semestre: 4, short: 'IN4' },
  { filiere_code: 'SLMII2', code: 'SLIN4305', nom: 'Programmation en Lang c', semestre: 4, short: 'IN4' },
  { filiere_code: 'SLMII2', code: 'SLIN4105', nom: 'Program Objet UML', semestre: 4, short: 'IN4' },
  { filiere_code: 'SLMII2', code: 'SLIN4205', nom: 'Programmation Web 1', semestre: 4, short: 'IN4' },
  { filiere_code: 'SLMII2', code: 'SLIN4405', nom: 'Systéme d\'exploitation 1', semestre: 4, short: 'IN4' },
  { filiere_code: 'SLMII2', code: 'SLIN4605', nom: 'Probabimlités et statistiques', semestre: 4, short: 'IN4' },
  { filiere_code: 'SLMIT1', code: 'SLMI1105', nom: 'Algébre1', semestre: 1, short: 'MI1' },
  { filiere_code: 'SLMIT1', code: 'SLMI1205', nom: 'Algébre2', semestre: 1, short: 'MI1' },
  { filiere_code: 'SLMIT1', code: 'SLMI1305', nom: 'Analyse1', semestre: 1, short: 'MI1' },
  { filiere_code: 'SLMIT1', code: 'SLMI1405', nom: 'Thérmodynamique', semestre: 1, short: 'MI1' },
  { filiere_code: 'SLMIT1', code: 'SLMI1505', nom: 'Mécanique du point', semestre: 1, short: 'MI1' },
  { filiere_code: 'SLMIT1', code: 'SLMI1605', nom: 'Informatique', semestre: 1, short: 'MI1' },
  { filiere_code: 'SLMIT1', code: 'SLMI1705', nom: 'MTU', semestre: 1, short: 'MI1' },
  { filiere_code: 'SLMIT1', code: 'SLMI2105', nom: 'Algébre1', semestre: 2, short: 'MI2' },
  { filiere_code: 'SLMIT1', code: 'SLMI2205', nom: 'Algébre2', semestre: 2, short: 'MI2' },
  { filiere_code: 'SLMIT1', code: 'SLMI2305', nom: 'Analyse1', semestre: 2, short: 'MI2' },
  { filiere_code: 'SLMIT1', code: 'SLMI2405', nom: 'Thérmodynamique', semestre: 2, short: 'MI2' },
  { filiere_code: 'SLMIT1', code: 'SLMI2505', nom: 'Mécanique du point', semestre: 2, short: 'MI2' },
  { filiere_code: 'SLMIT1', code: 'SLMI2605', nom: 'Informatique', semestre: 2, short: 'MI2' },
  { filiere_code: 'SLMIT1', code: 'SLMI2705', nom: 'MTU', semestre: 2, short: 'MI2' },
  { filiere_code: 'SLMIM3', code: 'SLMA5605', nom: 'Langues', semestre: 5, short: 'MA5' },
  { filiere_code: 'SLMIM3', code: 'SLMA5705', nom: 'Systeme de gestion de contenu', semestre: 5, short: 'MA5' },
  { filiere_code: 'SLMIM3', code: 'SLMA5105', nom: 'Analyse complexe', semestre: 5, short: 'MA5' },
  { filiere_code: 'SLMIM3', code: 'SLMA5205', nom: 'Topologie', semestre: 5, short: 'MA5' },
  { filiere_code: 'SLMIM3', code: 'SLMA5305', nom: 'Mesure et Integration', semestre: 5, short: 'MA5' },
  { filiere_code: 'SLMIM3', code: 'SLMA5405', nom: 'Calcul differentiel', semestre: 5, short: 'MA5' },
  { filiere_code: 'SLMIM3', code: 'SLMA5505', nom: 'Analyse Numerique 2', semestre: 5, short: 'MA5' },
  { filiere_code: 'SLMIM3', code: 'SLMA6605', nom: 'Langues', semestre: 6, short: 'MA6' },
  { filiere_code: 'SLMIM3', code: 'SLMA6705', nom: 'Systeme de gestion de contenu', semestre: 6, short: 'MA6' },
  { filiere_code: 'SLMIM3', code: 'SLMA6105', nom: 'Analyse complexe', semestre: 6, short: 'MA6' },
  { filiere_code: 'SLMIM3', code: 'SLMA6205', nom: 'Topologie', semestre: 6, short: 'MA6' },
  { filiere_code: 'SLMIM3', code: 'SLMA6305', nom: 'Mesure et Integration', semestre: 6, short: 'MA6' },
  { filiere_code: 'SLMIM3', code: 'SLMA6405', nom: 'Calcul differentiel', semestre: 6, short: 'MA6' },
  { filiere_code: 'SLMIM3', code: 'SLMA6505', nom: 'Analyse Numerique 2', semestre: 6, short: 'MA6' },
  { filiere_code: 'SLBGB3', code: 'SLBI5105', nom: 'Biocologie des écosystèmes et écolotoxicogie', semestre: 5, short: 'BI5' },
  { filiere_code: 'SLBGB3', code: 'SLBI5605', nom: 'Langues', semestre: 5, short: 'BI5' },
  { filiere_code: 'SLBGB3', code: 'SLBI5705', nom: 'Compétences numérique II:Excel avancé', semestre: 5, short: 'BI5' },
  { filiere_code: 'SLBGB3', code: 'SLBI5205', nom: 'Biophysique et techniques d\'analyses biomédicales', semestre: 5, short: 'BI5' },
  { filiere_code: 'SLBGB3', code: 'SLBI5405', nom: 'Génétique II et biologie moléculaire', semestre: 5, short: 'BI5' },
  { filiere_code: 'SLBGB3', code: 'SLBI5505', nom: 'Les bases fondamentales de l\'immunologie', semestre: 5, short: 'BI5' },
  { filiere_code: 'SLBGB3', code: 'SLBI5305', nom: 'Physiologie humaine', semestre: 5, short: 'BI5' },
  { filiere_code: 'SLBGB3', code: 'SLBI6105', nom: 'Biocologie des écosystèmes et écolotoxicogie', semestre: 6, short: 'BI6' },
  { filiere_code: 'SLBGB3', code: 'SLBI6605', nom: 'Langues', semestre: 6, short: 'BI6' },
  { filiere_code: 'SLBGB3', code: 'SLBI6705', nom: 'Compétences numérique II:Excel avancé', semestre: 6, short: 'BI6' },
  { filiere_code: 'SLBGB3', code: 'SLBI6205', nom: 'Biophysique et techniques d\'analyses biomédicales', semestre: 6, short: 'BI6' },
  { filiere_code: 'SLBGB3', code: 'SLBI6405', nom: 'Génétique II et biologie moléculaire', semestre: 6, short: 'BI6' },
  { filiere_code: 'SLBGB3', code: 'SLBI6505', nom: 'Les bases fondamentales de l\'immunologie', semestre: 6, short: 'BI6' },
  { filiere_code: 'SLBGB3', code: 'SLBI6305', nom: 'Physiologie humaine', semestre: 6, short: 'BI6' },
  { filiere_code: 'SLBGB2', code: 'SLBI3105', nom: 'Biochimie structurale', semestre: 3, short: 'BI3' },
  { filiere_code: 'SLBGB2', code: 'SLBI3205', nom: 'Microbiologie générale', semestre: 3, short: 'BI3' },
  { filiere_code: 'SLBGB2', code: 'SLBI3405', nom: 'Techniques d\'analyse', semestre: 3, short: 'BI3' },
  { filiere_code: 'SLBGB2', code: 'SLBI3504', nom: 'Biostatistiques', semestre: 3, short: 'BI3' },
  { filiere_code: 'SLBGB2', code: 'SLBI3305', nom: 'Ecologie générale', semestre: 3, short: 'BI3' },
  { filiere_code: 'SLBGB2', code: 'SLBI3705', nom: 'Langues', semestre: 3, short: 'BI3' },
  { filiere_code: 'SLBGB2', code: 'SLBI3605', nom: 'Informatique pour la biologie', semestre: 3, short: 'BI3' },
  { filiere_code: 'SLBGB2', code: 'SLBI4105', nom: 'Biochimie structurale', semestre: 4, short: 'BI4' },
  { filiere_code: 'SLBGB2', code: 'SLBI4205', nom: 'Microbiologie générale', semestre: 4, short: 'BI4' },
  { filiere_code: 'SLBGB2', code: 'SLBI4405', nom: 'Techniques d\'analyse', semestre: 4, short: 'BI4' },
  { filiere_code: 'SLBGB2', code: 'SLBI4504', nom: 'Biostatistiques', semestre: 4, short: 'BI4' },
  { filiere_code: 'SLBGB2', code: 'SLBI4305', nom: 'Ecologie générale', semestre: 4, short: 'BI4' },
  { filiere_code: 'SLBGB2', code: 'SLBI4705', nom: 'Langues', semestre: 4, short: 'BI4' },
  { filiere_code: 'SLBGB2', code: 'SLBI4605', nom: 'Informatique pour la biologie', semestre: 4, short: 'BI4' },
  { filiere_code: 'SLPCP3', code: 'SLPH5305', nom: 'Physique des matériaux', semestre: 5, short: 'PH5' },
  { filiere_code: 'SLPCP3', code: 'SLPH5605', nom: 'Module transversal', semestre: 5, short: 'PH5' },
  { filiere_code: 'SLPCP3', code: 'SLPH5205', nom: 'Electronique', semestre: 5, short: 'PH5' },
  { filiere_code: 'SLPCP3', code: 'SLPH5105', nom: 'Mécanique analytique & vibration', semestre: 5, short: 'PH5' },
  { filiere_code: 'SLPCP3', code: 'SLPH5505', nom: 'Physique nucléaire', semestre: 5, short: 'PH5' },
  { filiere_code: 'SLPCP3', code: 'SLPH5705', nom: 'Langue étrangère 2', semestre: 5, short: 'PH5' },
  { filiere_code: 'SLPCP3', code: 'SLPH6305', nom: 'Physique des matériaux', semestre: 6, short: 'PH6' },
  { filiere_code: 'SLPCP3', code: 'SLPH6605', nom: 'Module transversal', semestre: 6, short: 'PH6' },
  { filiere_code: 'SLPCP3', code: 'SLPH6205', nom: 'Electronique', semestre: 6, short: 'PH6' },
  { filiere_code: 'SLPCP3', code: 'SLPH6105', nom: 'Mécanique analytique & vibration', semestre: 6, short: 'PH6' },
  { filiere_code: 'SLPCP3', code: 'SLPH6505', nom: 'Physique nucléaire', semestre: 6, short: 'PH6' },
  { filiere_code: 'SLPCP3', code: 'SLPH6705', nom: 'Langue étrangère 2', semestre: 6, short: 'PH6' },
  { filiere_code: 'SLPCC2', code: 'SLCH3105', nom: 'Chimie descriptive I', semestre: 3, short: 'CH3' },
  { filiere_code: 'SLPCC2', code: 'SLCH3305', nom: 'Chimie des électrolytes', semestre: 3, short: 'CH3' },
  { filiere_code: 'SLPCC2', code: 'SLCH3405', nom: 'Mathématiques-Chimie', semestre: 3, short: 'CH3' },
  { filiere_code: 'SLPCC2', code: 'SLCH3505', nom: 'Electromagnétisme', semestre: 3, short: 'CH3' },
  { filiere_code: 'SLPCC2', code: 'SLCH3605', nom: 'Algorithmique & programmation python', semestre: 3, short: 'CH3' },
  { filiere_code: 'SLPCC2', code: 'SLCH3705', nom: 'Langues', semestre: 3, short: 'CH3' },
  { filiere_code: 'SLPCC2', code: 'SLCH3205', nom: 'Chimie organique générale', semestre: 3, short: 'CH3' },
  { filiere_code: 'SLPCC2', code: 'SLCH4105', nom: 'Chimie descriptive I', semestre: 4, short: 'CH4' },
  { filiere_code: 'SLPCC2', code: 'SLCH4305', nom: 'Chimie des électrolytes', semestre: 4, short: 'CH4' },
  { filiere_code: 'SLPCC2', code: 'SLCH4405', nom: 'Mathématiques-Chimie', semestre: 4, short: 'CH4' },
  { filiere_code: 'SLPCC2', code: 'SLCH4505', nom: 'Electromagnétisme', semestre: 4, short: 'CH4' },
  { filiere_code: 'SLPCC2', code: 'SLCH4605', nom: 'Algorithmique & programmation python', semestre: 4, short: 'CH4' },
  { filiere_code: 'SLPCC2', code: 'SLCH4705', nom: 'Langues', semestre: 4, short: 'CH4' },
  { filiere_code: 'SLPCC2', code: 'SLCH4205', nom: 'Chimie organique générale', semestre: 4, short: 'CH4' },
  { filiere_code: 'SLGEP3', code: 'SLPH5405', nom: 'Physique statistique', semestre: 5, short: 'PH5' },
  { filiere_code: 'SLGEP3', code: 'SLPH6405', nom: 'Physique statistique', semestre: 6, short: 'PH6' },
  { filiere_code: 'SLMII3', code: 'SLIN5105', nom: 'Algorithmique et Programmation en python', semestre: 5, short: 'IN5' },
  { filiere_code: 'SLMII3', code: 'SLIN5205', nom: 'Recherche operationnelle', semestre: 5, short: 'IN5' },
  { filiere_code: 'SLMII3', code: 'SLIN5305', nom: 'Bases de données avancée', semestre: 5, short: 'IN5' },
  { filiere_code: 'SLMII3', code: 'SLIN5405', nom: 'Langage de modélisation unifié UML', semestre: 5, short: 'IN5' },
  { filiere_code: 'SLMII3', code: 'SLIN5505', nom: 'Programmation OB JAVA', semestre: 5, short: 'IN5' },
  { filiere_code: 'SLMII3', code: 'SLIN5605', nom: 'Réseaux', semestre: 5, short: 'IN5' },
  { filiere_code: 'SLMII3', code: 'SLIN5705', nom: 'Langues(Anglais)', semestre: 5, short: 'IN5' },
  { filiere_code: 'SLMII3', code: 'SLIN6105', nom: 'Algorithmique et Programmation en python', semestre: 6, short: 'IN6' },
  { filiere_code: 'SLMII3', code: 'SLIN6205', nom: 'Recherche operationnelle', semestre: 6, short: 'IN6' },
  { filiere_code: 'SLMII3', code: 'SLIN6305', nom: 'Bases de données avancée', semestre: 6, short: 'IN6' },
  { filiere_code: 'SLMII3', code: 'SLIN6405', nom: 'Langage de modélisation unifié UML', semestre: 6, short: 'IN6' },
  { filiere_code: 'SLMII3', code: 'SLIN6505', nom: 'Programmation OB JAVA', semestre: 6, short: 'IN6' },
  { filiere_code: 'SLMII3', code: 'SLIN6605', nom: 'Réseaux', semestre: 6, short: 'IN6' },
  { filiere_code: 'SLMII3', code: 'SLIN6705', nom: 'Langues(Anglais)', semestre: 6, short: 'IN6' },
  { filiere_code: 'SLCPC3', code: 'SLCP5105', nom: 'Techniques Spectroscopiques d\'analyse', semestre: 5, short: 'CP5' },
  { filiere_code: 'SLCPC3', code: 'SLCP5305', nom: 'Radiocristallographie et cristallochimie II', semestre: 5, short: 'CP5' },
  { filiere_code: 'SLCPC3', code: 'SLCP5405', nom: 'Electrochimie', semestre: 5, short: 'CP5' },
  { filiere_code: 'SLCPC3', code: 'SLCP5505', nom: 'Cinétique et réacteurs chimiques', semestre: 5, short: 'CP5' },
  { filiere_code: 'SLCPC3', code: 'SLCP5605', nom: 'Anglais', semestre: 5, short: 'CP5' },
  { filiere_code: 'SLCPC3', code: 'SLCP5705', nom: 'Digital Skills II : Excel avancé', semestre: 5, short: 'CP5' },
  { filiere_code: 'SLCPC3', code: 'SLCP5205', nom: 'Chimie organique fonctionnelle', semestre: 5, short: 'CP5' },
  { filiere_code: 'SLCPC3', code: 'SLCP6105', nom: 'Techniques Spectroscopiques d\'analyse', semestre: 6, short: 'CP6' },
  { filiere_code: 'SLCPC3', code: 'SLCP6305', nom: 'Radiocristallographie et cristallochimie II', semestre: 6, short: 'CP6' },
  { filiere_code: 'SLCPC3', code: 'SLCP6405', nom: 'Electrochimie', semestre: 6, short: 'CP6' },
  { filiere_code: 'SLCPC3', code: 'SLCP6505', nom: 'Cinétique et réacteurs chimiques', semestre: 6, short: 'CP6' },
  { filiere_code: 'SLCPC3', code: 'SLCP6605', nom: 'Anglais', semestre: 6, short: 'CP6' },
  { filiere_code: 'SLCPC3', code: 'SLCP6705', nom: 'Digital Skills II : Excel avancé', semestre: 6, short: 'CP6' },
  { filiere_code: 'SLCPC3', code: 'SLCP6205', nom: 'Chimie organique fonctionnelle', semestre: 6, short: 'CP6' },
  { filiere_code: 'SLMIM2', code: 'SLMA3105', nom: 'Analyse4', semestre: 3, short: 'MA3' },
  { filiere_code: 'SLMIM2', code: 'SLMA3205', nom: 'analyse5', semestre: 3, short: 'MA3' },
  { filiere_code: 'SLMIM2', code: 'SLMA3605', nom: 'Mécanique du solide', semestre: 3, short: 'MA3' },
  { filiere_code: 'SLMIM2', code: 'SLMA3305', nom: 'Algebre4', semestre: 3, short: 'MA3' },
  { filiere_code: 'SLMIM2', code: 'SLMA3405', nom: 'Probabilités et statistiques', semestre: 3, short: 'MA3' },
  { filiere_code: 'SLMIM2', code: 'SLMA3505', nom: 'Informatique 3', semestre: 3, short: 'MA3' },
  { filiere_code: 'SLMIM2', code: 'SLMA3705', nom: 'Langues', semestre: 3, short: 'MA3' },
  { filiere_code: 'SLMIM2', code: 'SLMA4105', nom: 'Analyse4', semestre: 4, short: 'MA4' },
  { filiere_code: 'SLMIM2', code: 'SLMA4205', nom: 'analyse5', semestre: 4, short: 'MA4' },
  { filiere_code: 'SLMIM2', code: 'SLMA4605', nom: 'Mécanique du solide', semestre: 4, short: 'MA4' },
  { filiere_code: 'SLMIM2', code: 'SLMA4305', nom: 'Algebre4', semestre: 4, short: 'MA4' },
  { filiere_code: 'SLMIM2', code: 'SLMA4405', nom: 'Probabilités et statistiques', semestre: 4, short: 'MA4' },
  { filiere_code: 'SLMIM2', code: 'SLMA4505', nom: 'Informatique 3', semestre: 4, short: 'MA4' },
  { filiere_code: 'SLMIM2', code: 'SLMA4705', nom: 'Langues', semestre: 4, short: 'MA4' },
  { filiere_code: 'SLIAI3', code: 'SLIA5105', nom: '-Algorithmique et programmation em pyton', semestre: 5, short: 'IA5' },
  { filiere_code: 'SLIAI3', code: 'SLIA5205', nom: 'Technologies et ingénierie avancée du web', semestre: 5, short: 'IA5' },
  { filiere_code: 'SLIAI3', code: 'SLIA5305', nom: 'Analyse et visualisation des données', semestre: 5, short: 'IA5' },
  { filiere_code: 'SLIAI3', code: 'SLIA5405', nom: 'Programmation orientée objet-java', semestre: 5, short: 'IA5' },
  { filiere_code: 'SLIAI3', code: 'SLIA5505', nom: 'Analyse des donnés', semestre: 5, short: 'IA5' },
  { filiere_code: 'SLIAI3', code: 'SLIA5605', nom: 'Bases de données avancée', semestre: 5, short: 'IA5' },
  { filiere_code: 'SLIAI3', code: 'SLIA5705', nom: 'Langues : Anglais', semestre: 5, short: 'IA5' },
  { filiere_code: 'SLIAI3', code: 'SLIA6105', nom: '-Algorithmique et programmation em pyton', semestre: 6, short: 'IA6' },
  { filiere_code: 'SLIAI3', code: 'SLIA6205', nom: 'Technologies et ingénierie avancée du web', semestre: 6, short: 'IA6' },
  { filiere_code: 'SLIAI3', code: 'SLIA6305', nom: 'Analyse et visualisation des données', semestre: 6, short: 'IA6' },
  { filiere_code: 'SLIAI3', code: 'SLIA6405', nom: 'Programmation orientée objet-java', semestre: 6, short: 'IA6' },
  { filiere_code: 'SLIAI3', code: 'SLIA6505', nom: 'Analyse des donnés', semestre: 6, short: 'IA6' },
  { filiere_code: 'SLIAI3', code: 'SLIA6605', nom: 'Bases de données avancée', semestre: 6, short: 'IA6' },
  { filiere_code: 'SLIAI3', code: 'SLIA6705', nom: 'Langues : Anglais', semestre: 6, short: 'IA6' },
  { filiere_code: 'SMSGM1', code: 'MGM11104', nom: 'Géologie et Géomorphologie côtières et marines', semestre: 1, short: 'MGM1' },
  { filiere_code: 'SMSGM1', code: 'MGM11204', nom: 'Sédimentologie et géotechnique côtières et marines', semestre: 1, short: 'MGM1' },
  { filiere_code: 'SMSGM1', code: 'MGM11304', nom: 'Océanographie biologique', semestre: 1, short: 'MGM1' },
  { filiere_code: 'SMSGM1', code: 'MGM11404', nom: 'Risques côtiers et changements climatiques', semestre: 1, short: 'MGM1' },
  { filiere_code: 'SMSGM1', code: 'MGM11504', nom: 'SIG et Télédétection spatiale', semestre: 1, short: 'MGM1' },
  { filiere_code: 'SMSGM1', code: 'MGM11604', nom: 'Langues  Communication & Soft Skills', semestre: 1, short: 'MGM1' },
  { filiere_code: 'SMSGM1', code: 'MGM21104', nom: 'Géologie et Géomorphologie côtières et marines', semestre: 2, short: 'MGM2' },
  { filiere_code: 'SMSGM1', code: 'MGM21204', nom: 'Sédimentologie et géotechnique côtières et marines', semestre: 2, short: 'MGM2' },
  { filiere_code: 'SMSGM1', code: 'MGM21304', nom: 'Océanographie biologique', semestre: 2, short: 'MGM2' },
  { filiere_code: 'SMSGM1', code: 'MGM21404', nom: 'Risques côtiers et changements climatiques', semestre: 2, short: 'MGM2' },
  { filiere_code: 'SMSGM1', code: 'MGM21504', nom: 'SIG et Télédétection spatiale', semestre: 2, short: 'MGM2' },
  { filiere_code: 'SMSGM1', code: 'MGM21604', nom: 'Langues  Communication & Soft Skills', semestre: 2, short: 'MGM2' },
  { filiere_code: 'SLBGG2', code: 'SLGE3105', nom: 'Tectonique Analytique', semestre: 3, short: 'GE3' },
  { filiere_code: 'SLBGG2', code: 'SLGE3205', nom: 'Tectonique globale', semestre: 3, short: 'GE3' },
  { filiere_code: 'SLBGG2', code: 'SLGE3305', nom: 'Pétrologie magmatique', semestre: 3, short: 'GE3' },
  { filiere_code: 'SLBGG2', code: 'SLGE3405', nom: 'Pétrologie métamorphique', semestre: 3, short: 'GE3' },
  { filiere_code: 'SLBGG2', code: 'SLGE3605', nom: 'Hydrog&ologie et hydrologie', semestre: 3, short: 'GE3' },
  { filiere_code: 'SLBGG2', code: 'SLGE3705', nom: 'Langues', semestre: 3, short: 'GE3' },
  { filiere_code: 'SLBGG2', code: 'SLGE3505', nom: 'Pétrographie sédimentaire', semestre: 3, short: 'GE3' },
  { filiere_code: 'SLBGG2', code: 'SLGE4105', nom: 'Tectonique Analytique', semestre: 4, short: 'GE4' },
  { filiere_code: 'SLBGG2', code: 'SLGE4205', nom: 'Tectonique globale', semestre: 4, short: 'GE4' },
  { filiere_code: 'SLBGG2', code: 'SLGE4305', nom: 'Pétrologie magmatique', semestre: 4, short: 'GE4' },
  { filiere_code: 'SLBGG2', code: 'SLGE4405', nom: 'Pétrologie métamorphique', semestre: 4, short: 'GE4' },
  { filiere_code: 'SLBGG2', code: 'SLGE4605', nom: 'Hydrog&ologie et hydrologie', semestre: 4, short: 'GE4' },
  { filiere_code: 'SLBGG2', code: 'SLGE4705', nom: 'Langues', semestre: 4, short: 'GE4' },
  { filiere_code: 'SLBGG2', code: 'SLGE4505', nom: 'Pétrographie sédimentaire', semestre: 4, short: 'GE4' },
  { filiere_code: 'SFBVV3', code: 'SFV35104', nom: 'Physiologie des grandes fonctions', semestre: 3, short: 'SFV3' },
  { filiere_code: 'SFBVV3', code: 'SFV35204', nom: 'Croissance et developpement  des plantes', semestre: 3, short: 'SFV3' },
  { filiere_code: 'SFBVV3', code: 'SFV35404', nom: 'Immunologie', semestre: 3, short: 'SFV3' },
  { filiere_code: 'SFBVV3', code: 'SFV35504', nom: 'Génétique', semestre: 3, short: 'SFV3' },
  { filiere_code: 'SFBVV3', code: 'SFV35604', nom: 'Biologie moléculaire', semestre: 3, short: 'SFV3' },
  { filiere_code: 'SFBVV3', code: 'SFV35304', nom: 'Ecologie générale II', semestre: 3, short: 'SFV3' },
  { filiere_code: 'SFBVV3', code: 'SFV45104', nom: 'Physiologie des grandes fonctions', semestre: 4, short: 'SFV4' },
  { filiere_code: 'SFBVV3', code: 'SFV45204', nom: 'Croissance et developpement  des plantes', semestre: 4, short: 'SFV4' },
  { filiere_code: 'SFBVV3', code: 'SFV45404', nom: 'Immunologie', semestre: 4, short: 'SFV4' },
  { filiere_code: 'SFBVV3', code: 'SFV45504', nom: 'Génétique', semestre: 4, short: 'SFV4' },
  { filiere_code: 'SFBVV3', code: 'SFV45604', nom: 'Biologie moléculaire', semestre: 4, short: 'SFV4' },
  { filiere_code: 'SFBVV3', code: 'SFV45304', nom: 'Ecologie générale II', semestre: 4, short: 'SFV4' },
  { filiere_code: 'SBENV2', code: 'SBE23104', nom: 'Gestion de la Biodiversit', semestre: 2, short: 'SBE2' },
  { filiere_code: 'SBENV2', code: 'SBE23204', nom: 'Génétique / Epidémiologie', semestre: 2, short: 'SBE2' },
  { filiere_code: 'SBENV2', code: 'SBE23304', nom: 'Substances Naturelles : Phytochimie & applications', semestre: 2, short: 'SBE2' },
  { filiere_code: 'SBENV2', code: 'SBE23404', nom: 'Génomique fonctionnelle', semestre: 2, short: 'SBE2' },
  { filiere_code: 'SBENV2', code: 'SBE23504', nom: 'Propriété intellectuelle et rédaction des brevets', semestre: 2, short: 'SBE2' },
  { filiere_code: 'SBENV2', code: 'SBE23604', nom: 'Ecologie et gestion', semestre: 2, short: 'SBE2' },
  { filiere_code: 'SBENV2', code: 'SBE23704', nom: 'Ressources halieutiques au Maroc : Gestion et conservation', semestre: 2, short: 'SBE2' },
  { filiere_code: 'SFPCC3', code: 'SFC35104', nom: 'Chimie organique fonctionnelle', semestre: 3, short: 'SFC3' },
  { filiere_code: 'SFPCC3', code: 'SFC35204', nom: 'Radiocristallographie et cristallochimie II', semestre: 3, short: 'SFC3' },
  { filiere_code: 'SFPCC3', code: 'SFC35304', nom: 'Cinétique et catalyse', semestre: 3, short: 'SFC3' },
  { filiere_code: 'SFPCC3', code: 'SFC35404', nom: 'Chimie théorique', semestre: 3, short: 'SFC3' },
  { filiere_code: 'SFPCC3', code: 'SFC35504', nom: 'Electrochimie', semestre: 3, short: 'SFC3' },
  { filiere_code: 'SFPCC3', code: 'SFC35604', nom: 'Techniques spectroscopiques d\'analyse (UV-IR  RMN 1H,masse)', semestre: 3, short: 'SFC3' },
  { filiere_code: 'SFPCC3', code: 'SFC45104', nom: 'Chimie organique fonctionnelle', semestre: 4, short: 'SFC4' },
  { filiere_code: 'SFPCC3', code: 'SFC45204', nom: 'Radiocristallographie et cristallochimie II', semestre: 4, short: 'SFC4' },
  { filiere_code: 'SFPCC3', code: 'SFC45304', nom: 'Cinétique et catalyse', semestre: 4, short: 'SFC4' },
  { filiere_code: 'SFPCC3', code: 'SFC45404', nom: 'Chimie théorique', semestre: 4, short: 'SFC4' },
  { filiere_code: 'SFPCC3', code: 'SFC45504', nom: 'Electrochimie', semestre: 4, short: 'SFC4' },
  { filiere_code: 'SFPCC3', code: 'SFC45604', nom: 'Techniques spectroscopiques d\'analyse (UV-IR  RMN 1H,masse)', semestre: 4, short: 'SFC4' },
  { filiere_code: 'SFPCP3', code: 'SFP35204', nom: 'Mécanique analytique et vibrations', semestre: 3, short: 'SFP3' },
  { filiere_code: 'SFPCP3', code: 'SFP35304', nom: 'Physique nucléaire', semestre: 3, short: 'SFP3' },
  { filiere_code: 'SFPCP3', code: 'SFP35404', nom: 'Physique des matériaux', semestre: 3, short: 'SFP3' },
  { filiere_code: 'SFPCP3', code: 'SFP35504', nom: 'Physique quantique', semestre: 3, short: 'SFP3' },
  { filiere_code: 'SFPCP3', code: 'SFP35604', nom: 'Physique statistique', semestre: 3, short: 'SFP3' },
  { filiere_code: 'SFPCP3', code: 'SFP35104', nom: 'Electronique analogique', semestre: 3, short: 'SFP3' },
  { filiere_code: 'SFPCP3', code: 'SFP45204', nom: 'Mécanique analytique et vibrations', semestre: 4, short: 'SFP4' },
  { filiere_code: 'SFPCP3', code: 'SFP45304', nom: 'Physique nucléaire', semestre: 4, short: 'SFP4' },
  { filiere_code: 'SFPCP3', code: 'SFP45404', nom: 'Physique des matériaux', semestre: 4, short: 'SFP4' },
  { filiere_code: 'SFPCP3', code: 'SFP45504', nom: 'Physique quantique', semestre: 4, short: 'SFP4' },
  { filiere_code: 'SFPCP3', code: 'SFP45604', nom: 'Physique statistique', semestre: 4, short: 'SFP4' },
  { filiere_code: 'SFPCP3', code: 'SFP45104', nom: 'Electronique analogique', semestre: 4, short: 'SFP4' },
  { filiere_code: 'SLBGG3', code: 'SLGE5705', nom: 'Power skills', semestre: 5, short: 'GE5' },
  { filiere_code: 'SLBGG3', code: 'SLGE5205', nom: 'Ecole de terrain', semestre: 5, short: 'GE5' },
  { filiere_code: 'SLBGG3', code: 'SLGE5305', nom: 'Introduction à la géotechnique', semestre: 5, short: 'GE5' },
  { filiere_code: 'SLBGG3', code: 'SLGE5605', nom: 'Langues étrangères', semestre: 5, short: 'GE5' },
  { filiere_code: 'SLBGG3', code: 'SLGE5105', nom: 'Géologie et Goressources marines et littorales', semestre: 5, short: 'GE5' },
  { filiere_code: 'SLBGG3', code: 'SLGE5405', nom: 'Cartographie thématique et topographie', semestre: 5, short: 'GE5' },
  { filiere_code: 'SLBGG3', code: 'SLGE5505', nom: 'Géophysique', semestre: 5, short: 'GE5' },
  { filiere_code: 'SLBGG3', code: 'SLGE6705', nom: 'Power skills', semestre: 6, short: 'GE6' },
  { filiere_code: 'SLBGG3', code: 'SLGE6205', nom: 'Ecole de terrain', semestre: 6, short: 'GE6' },
  { filiere_code: 'SLBGG3', code: 'SLGE6305', nom: 'Introduction à la géotechnique', semestre: 6, short: 'GE6' },
  { filiere_code: 'SLBGG3', code: 'SLGE6605', nom: 'Langues étrangères', semestre: 6, short: 'GE6' },
  { filiere_code: 'SLBGG3', code: 'SLGE6105', nom: 'Géologie et Goressources marines et littorales', semestre: 6, short: 'GE6' },
  { filiere_code: 'SLBGG3', code: 'SLGE6405', nom: 'Cartographie thématique et topographie', semestre: 6, short: 'GE6' },
  { filiere_code: 'SLBGG3', code: 'SLGE6505', nom: 'Géophysique', semestre: 6, short: 'GE6' },
  { filiere_code: 'SFAII3', code: 'SFA35104', nom: 'Topologie', semestre: 3, short: 'SFA3' },
  { filiere_code: 'SFAII3', code: 'SFA35204', nom: 'Intégration', semestre: 3, short: 'SFA3' },
  { filiere_code: 'SFAII3', code: 'SFA35304', nom: 'Calcul différentiel', semestre: 3, short: 'SFA3' },
  { filiere_code: 'SFAII3', code: 'SFA35504', nom: 'Analyse numérique 2', semestre: 3, short: 'SFA3' },
  { filiere_code: 'SFAII3', code: 'SFA35404', nom: 'Programmation Mathématique', semestre: 3, short: 'SFA3' },
  { filiere_code: 'SFAII3', code: 'SFA35604', nom: 'Informatique 5 :Programmation orientée objet ', semestre: 3, short: 'SFA3' },
  { filiere_code: 'SFAII3', code: 'SFA45104', nom: 'Topologie', semestre: 4, short: 'SFA4' },
  { filiere_code: 'SFAII3', code: 'SFA45204', nom: 'Intégration', semestre: 4, short: 'SFA4' },
  { filiere_code: 'SFAII3', code: 'SFA45304', nom: 'Calcul différentiel', semestre: 4, short: 'SFA4' },
  { filiere_code: 'SFAII3', code: 'SFA45504', nom: 'Analyse numérique 2', semestre: 4, short: 'SFA4' },
  { filiere_code: 'SFAII3', code: 'SFA45404', nom: 'Programmation Mathématique', semestre: 4, short: 'SFA4' },
  { filiere_code: 'SFAII3', code: 'SFA45604', nom: 'Informatique 5 :Programmation orientée objet ', semestre: 4, short: 'SFA4' },
];

export async function POST() {
  const conn = await pool.getConnection();
  try {
    await conn.query('SET NAMES utf8mb4');

    await conn.query(`CREATE TABLE IF NOT EXISTS sessions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      nom VARCHAR(100) NOT NULL UNIQUE,
      type ENUM('automne','printemps') NOT NULL,
      annee VARCHAR(20) NOT NULL
    )`);

    await conn.query(`CREATE TABLE IF NOT EXISTS filieres (
      id INT AUTO_INCREMENT PRIMARY KEY,
      code VARCHAR(20) NOT NULL UNIQUE,
      nom VARCHAR(200) NOT NULL,
      semestre INT NOT NULL,
      short_base VARCHAR(20) NOT NULL
    )`);

    await conn.query(`CREATE TABLE IF NOT EXISTS modules (
      id INT AUTO_INCREMENT PRIMARY KEY,
      filiere_id INT NOT NULL,
      code VARCHAR(20) NOT NULL,
      nom VARCHAR(250) NOT NULL,
      semestre INT NOT NULL,
      short VARCHAR(20) NOT NULL,
      FOREIGN KEY (filiere_id) REFERENCES filieres(id),
      UNIQUE KEY uq_mod (code)
    )`);

    await conn.query(`CREATE TABLE IF NOT EXISTS planning (
      id INT AUTO_INCREMENT PRIMARY KEY,
      module_id INT NOT NULL,
      session_id INT NOT NULL,
      jour DATE NOT NULL,
      periode ENUM('matin','apres-midi') NOT NULL,
      FOREIGN KEY (module_id) REFERENCES modules(id),
      FOREIGN KEY (session_id) REFERENCES sessions(id)
    )`);

    for (const f of FILIERES) {
      await conn.query(
        'INSERT IGNORE INTO filieres (code, nom, semestre, short_base) VALUES (?, ?, ?, ?)',
        [f.code, f.nom, f.semestre, f.short_base]
      );
    }

    for (const m of MODULES) {
      await conn.query(
        `INSERT IGNORE INTO modules (filiere_id, code, nom, semestre, short)
         SELECT id, ?, ?, ?, ? FROM filieres WHERE code = ?`,
        [m.code, m.nom, m.semestre, m.short, m.filiere_code]
      );
    }

    return NextResponse.json({ success: true });
  } catch (err) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  } finally {
    conn.release();
  }
}
